--- 
- name: Vagrant Install Digital Rebar by RackN 2015
  # based on https://github.com/digitalrebar/doc
  hosts: all
  sudo: yes
  tasks:
    - include: tasks/centos07-base.yml
      when: ansible_os_family == "RedHat"
    - include: tasks/ubuntu1404-base.yml
      when: ansible_os_family == "Debian"
    - include: tasks/docker.yml

    - name: Make cache dirs
      command: mkdir -p .cache/digitalrebar/tftpboot/isos
      ignore_errors: yes
    - name: download Ubuntu ISO [BACKGROUND] (see list https://github.com/digitalrebar/core/blob/develop/barclamps/provisioner.yml)
      command: su -c "nohup wget http://mirrors.kernel.org/ubuntu-releases/trusty/ubuntu-14.04.3-server-amd64.iso -nc -O ubuntu-14.04.2-server-amd64.iso &"
      args:
        creates: ubuntu-14.04.2-server-amd64.iso
        chdir: .cache/digitalrebar/tftpboot/isos
    - name: download Centos ISO [BACKGROUND] (see list https://github.com/digitalrebar/core/blob/develop/barclamps/provisioner.yml)
      command: su -c "nohup wget http://mirrors.kernel.org/centos/7.1.1503/isos/x86_64/CentOS-7-x86_64-Minimal-1503-01.iso -nc &"
      args:
        creates: CentOS-7-x86_64-Minimal-1503-01.iso
        chdir: .cache/digitalrebar/tftpboot/isos

    - name: allow docker access after reboot
      command: sudo usermod -a -G docker vagrant
    - name: create SSH key for host to access slaves
      command: ssh-keygen -t rsa -f '.ssh/id_rsa' -P ''
      args:
        creates: .ssh/id_rsa.pub

    - name: get code from local system
      synchronize: src=./compose dest=~ rsync_path="rsync"
    - name: remove rebar-key file
      file: path=/home/vagrant/compose/data-dir/node/rebar-key.sh state=absent

    - name: setup compose
      command: ./setup.sh
      args:
        chdir: /home/vagrant/compose
        creates: compose/digitalrebar/core
      ignore_errors: yes
    - name: copy user ssh public key to rebar
      command: cp .ssh/id_rsa.pub compose/digitalrebar/core/config/ssh_keys/setup-0.key
      args:
        creates: compose/digitalrebar/core/config/ssh_keys/setup-0.key

    - name: Pull Digital Rebar Images [SLOW]
      command: docker-compose pull
      args:
        chdir: /home/vagrant/compose
    - name: Compose up Digital Rebar Infrastructre
      command: docker-compose up -d
      args:
        chdir: /home/vagrant/compose

    - name: wait until service is up (1 to 10 minutes)
      wait_for: port=3000 delay=60 timeout=600
    - name: wait for rebar-key (1 to 30 minutes)
      wait_for: path=/home/vagrant/compose/data-dir/node/rebar-key.sh state=present delay=60 timeout=1800
    - name: copy rebar key to shared area
      command: cp /home/vagrant/compose/data-dir/node/rebar-key.sh /vagrant/rebar-key.sh
      args:
        creates: /vagrant/rebar-key.sh
