---
  - name: Update repos
    command: yum makecache
    sudo: yes
  - name: Install Prereqs [SLOW]
    yum: name={{ item }} state=latest
    with_items:
      - git
      - screen
      - qemu-kvm
      - libvirt
      - bridge-utils
      - ruby-devel
      - make
      - curl
      - wget
      - gcc
      - psmisc
    sudo: yes
  - name: Install ruby-gems for CentOS/RedHat 6
    yum: name={{ item }} state=latest
    with_items:
      - rubygems
    when: (ansible_distribution == "RedHat" or ansible_distribution == "CentOS") and ansible_distribution_major_version == "6"
    sudo: yes
  - name: gem install kvm slaves
    command: sudo gem install json net-http-digest_auth
  # Docker will put back what it needs - firewalld on Centos7
  - name: Silly flush of iptables
    command: sudo iptables -F
    ignore_errors: yes

