---
  - name: Update repos
    command: yum makecache
  - name: Install Prereqs [SLOW]
    yum: name={{ item }} state=latest
    with_items:
      - git
      - screen
      - qemu-kvm
      - libvirt
      - bridge-utils
      - ruby-devel
      - make
      - curl
      - wget
      - gcc
      - psmisc
  - name: Install ruby-gems for CentOS/RedHat 6
    yum: name={{ item }} state=latest
    with_items:
      - rubygems
    when: (ansible_distribution == "RedHat" or ansibile_distribution == "CentOS") and ansible_distribution_major_version == "6"
  - name: gem install kvm slaves
    command: sudo gem install json net-http-digest_auth

