
consul:
  extends:
    file: docker-compose-common.yml
    service: consul
  ports:
    - "127.0.0.1:8500:8500"

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres
  links:
    - consul:consul

webproxy:
  extends:
    file: docker-compose-common.yml
    service: webproxy
  links:
    - consul:consul
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "3128:3128"
{{ END ACCESS_MODE==HOST }}

goiardi:
  extends:
    file: docker-compose-common.yml
    service: goiardi
  links:
    - consul:consul
    - postgres:database
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "4646:4646"
{{ END ACCESS_MODE==HOST }}

rebar_api:
  extends:
    file: docker-compose-common.yml
    service: rebar_api
  links:
    - consul:consul
    - postgres:database
    - goiardi:goiardi
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "3000:3000"
{{ END ACCESS_MODE==HOST }}

fogwrap:
  extends:
    file: docker-compose-common.yml
    service: fogwrap
  links:
    - consul:consul
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "3030:3030"
{{ END ACCESS_MODE==HOST }}
    
packetwrap:
  extends:
    file: docker-compose-common.yml
    service: packetwrap
  links:
    - consul:consul
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "3031:3031"
{{ END ACCESS_MODE==HOST }}

dns:
  extends:
    file: docker-compose-common.yml
    service: dns
  links:
    - consul:consul
{{ START ACCESS_MODE==FORWARDER }}
    - forwarder:forwarder
{{ END ACCESS_MODE==FORWARDER }}
{{ START ACCESS_MODE==HOST }}
  ports:
    - "53/udp:53/udp"
{{ END ACCESS_MODE==HOST }}

{{ START ACCESS_MODE==FORWARDER }}
forwarder:
  extends:
    file: docker-compose-common.yml
    service: forwarder
  links:
    - consul:consul
{{ END ACCESS_MODE==FORWARDER }}

{{ START ACCESS_MODE==HOST }}
ntp:
  extends:
    file: docker-compose-common.yml
    service: ntp
  links:
    - consul:consul
  ports:
    - "123/udp:123/udp"
    - "123:123"
{{ END ACCESS_MODE==HOST }}

