
consul:
  extends:
    file: docker-compose-common.yml
    service: consul

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres
  links:
    - consul:consul

webproxy:
  extends:
    file: docker-compose-common.yml
    service: webproxy
  links:
    - consul:consul
    - forwarder:forwarder

goiardi:
  extends:
    file: docker-compose-common.yml
    service: goiardi
  links:
    - consul:consul
    - postgres:database

rebar_api:
  extends:
    file: docker-compose-common.yml
    service: rebar_api
  links:
    - consul:consul
    - postgres:database
    - goiardi:goiardi
    - forwarder:forwarder

dns:
  extends:
    file: docker-compose-common.yml
    service: dns
  links:
    - consul:consul
    - forwarder:forwarder

dhcp:
  extends:
    file: docker-compose-common.yml
    service: dhcp
  net: "container:forwarder"
  links:
    - consul:consul
    - forwarder:forwarder

provisioner:
  extends:
    file: docker-compose-common.yml
    service: provisioner
  links:
    - consul:consul
    - forwarder:forwarder

elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch

logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch:elasticsearch

kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  links:
    - elasticsearch:elasticsearch

logspout:
  net: container:logstash
  extends:
    file: docker-compose-common.yml
    service: logspout

cadvisor:
  extends:
    file: docker-compose-common.yml
    service: cadvisor

forwarder:
  extends:
    file: docker-compose-common.yml
    service: forwarder
  links:
    - consul:consul

node:
  extends:
    file: docker-compose-common.yml
    service: node
  links:
    - rebar_api:rebar_api
    - forwarder:forwarder
