
consul:
  extends:
    file: docker-compose-common.yml
    service: consul

postgres:
  extends:
    file: docker-compose-common.yml
    service: postgres
  links:
    - consul:consul

webproxy:
  extends:
    file: docker-compose-common.yml
    service: webproxy
  links:
    - consul:consul
  ports:
    - "3128:3128"

goiardi:
  extends:
    file: docker-compose-common.yml
    service: goiardi
  links:
    - consul:consul
    - postgres:database
  ports:
    - "4646:4646"

rebar_api:
  extends:
    file: docker-compose-common.yml
    service: rebar_api
  links:
    - consul:consul
    - postgres:database
    - goiardi:goiardi
  ports:
    - "3000:3000"

ntp:
  extends:
    file: docker-compose-common.yml
    service: ntp
  links:
    - consul:consul
  ports:
    - "123/udp:123/udp"
    - "123:123"

dns:
  extends:
    file: docker-compose-common.yml
    service: dns
  links:
    - consul:consul
  ports:
    - "53/udp:53/udp"

dhcp:
  extends:
    file: docker-compose-common.yml
    service: dhcp
  links:
    - consul:consul
  net: "host"

provisioner:
  extends:
    file: docker-compose-common.yml
    service: provisioner
  links:
    - consul:consul
  ports:
    - "69/udp:69/udp"
    - "8091:8091"

elasticsearch:
  extends:
    file: docker-compose-common.yml
    service: elasticsearch

logstash:
  extends:
    file: docker-compose-common.yml
    service: logstash
  links:
    - elasticsearch:elasticsearch

kibana:
  extends:
    file: docker-compose-common.yml
    service: kibana
  links:
    - elasticsearch:elasticsearch

logspout:
  net: container:logstash
  extends:
    file: docker-compose-common.yml
    service: logspout

cadvisor:
  extends:
    file: docker-compose-common.yml
    service: cadvisor

node:
  extends:
    file: docker-compose-common.yml
    service: node
  links:
    - rebar_api:rebar_api
