{
  "category": "admin",
  "group": "internal",
  "deployment": "system",
  "conduit": "dhcp",
  "v6prefix": "auto",
  "ranges": [
    {
      "name": "host",
      "first": "10.201.71.10/24",
      "last": "10.201.71.199/24",
      "allow_bound_leases": true
    },
    {
      "name": "dhcp",
      "first": "10.201.71.200/24",
      "last": "10.201.71.254/24",
      "allow_anon_leases": true
    }
  ],
  "router": {
    "address": "10.201.71.1/24",
    "pref": 10
  }
}
