---
  - name: Add python2.7 repo
    apt_repository: repo='ppa:fkrull/deadsnakes-python2.7'
    sudo: yes
  - name: Add ruby2.1 repo
    apt_repository: repo='ppa:brightbox/ruby-ng'
    sudo: yes
  - name: Update repos (was not working from apt:)
    command: sudo apt-get update -y
  - name: Update python [SLOW]
    command: sudo apt-get upgrade -y
  - name: Install Prereqs [SLOW]
    apt: name={{ item }} state=latest
    with_items:
      - git
      - wget
      - curl
      - python
      - python-pycurl
      - jq
    sudo: yes
  - name: Install Provisioner Prereqs [SLOW]
    apt: name={{ item }} state=latest
    with_items:
      - ruby2.1
      - ruby2.1-dev
      - screen
      - qemu-kvm
      - libvirt-bin
      - ubuntu-vm-builder
      - bridge-utils
      - make
      - gcc
    sudo: yes
    when: "'--provisioner' in dr_services"
  - name: Provisioner gem install kvm slaves
    command: sudo gem install json net-http-digest_auth
    args:
      creates: /var/lib/gems/2.1.0/gems/json-2.0.2
    sudo: yes
    when: "'--provisioner' in dr_services"
  - name: stop apparmor
    command: sudo service apparmor teardown
    sudo: yes
  - name: remove apparmor
    command: sudo update-rc.d -f apparmor remove
    sudo: yes
