---
- name: create docker service directory for systemd
  file: path=/etc/systemd/system/docker.service.d state=directory
  sudo: yes

- name: drop docker environment conf to enable proxy usage
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  sudo: yes
